#!/usr/bin/env bash

if [[ ! -d $1 ]]; then
  echo "usage: diffs <project-dir>" && exit 1
fi
PROJECT="$1"

files="README.md package.json"

for F in $files; do
  echo "############# Changes: $F #############"
  diff \{\{cookiecutter.repo_name\}\}/$F $PROJECT/$F
done
